### ISSUE TITLE
iPhone se 手机吧进不去

### ISSUE THREAD

**Issue by Huangshuboo** [Tangent-90/Coolapk-UWP#105]
![image](https://user-images.githubusercontent.com/53803830/116343190-9192dc80-a816-11eb-9195-66878e059c26.png)

好像类似的手机吧别的型号都进不去
![image](https://user-images.githubusercontent.com/53803830/116343327-cbfc7980-a816-11eb-9860-468c598266b1.png)

**Comment by wherewhere** [comment]
下次更新就支持了
