### ISSUE TITLE
一个bug

### ISSUE THREAD

**Issue by 1690783262** [Tangent-90/Coolapk-UWP#107]
![9923f7cd5aae3d7bcb79c0620bffcd33](https://user-images.githubusercontent.com/63230487/120418648-8130cd00-c393-11eb-8b32-bd59e2a4f773.jpg)
日志
[Log - 20210602.log](https://github.com/Tangent-90/Coolapk-UWP/files/6581745/Log.-.20210602.log)

**Comment by wherewhere** [comment]
具体描述一下。。。

**Comment by 1690783262** [comment]
> 具体描述一下。。。

请看一下这个视频   链接：https://pan.baidu.com/s/13pfk7oOVeJlUJfzKcsLw-A 
提取码：xdnr

**Comment by wherewhere** [comment]
> > 具体描述一下。。。
> 
> 请看一下这个视频             链接https://pan.baidu.com/s/13pfk7oOVeJlUJfzKcsLw-A 
> 提取码：xdnr 
> 

具体版本号，这个Bug不应该存在了

**Comment by 1690783262** [comment]
> > > 具体描述一下。。。
> > 
> > 
> > 请看一下这个视频链接https://pan.baidu.com/s/13pfk7oOVeJlUJfzKcsLw-A
> > 提取码：xdnr
> 
> 具体版本号，这个Bug不应该存在了

2.1.38

**Comment by wherewhere** [comment]
> > > > 具体描述一下。。。
> > > 
> > > 
> > > 请看一下这个视频链接https://pan.baidu.com/s/13pfk7oOVeJlUJfzKcsLw-A
> > > 提取码：xdnr
> > 
> > 具体版本号，这个Bug不应该存在了
> 
> 2.1.38

暂时无法重现，以后我遇到了再看看吧。。。

**Comment by 1690783262** [comment]
> > > > > 具体描述一下。。。
> > > > 
> > > > 
> > > > 请看一下这个视频链接https://pan.baidu.com/s/13pfk7oOVeJlUJfzKcsLw-A
> > > > 提取码：xdnr
> > > 
> > > 
> > > 具体版本号，这个Bug不应该存在了
> > 
> > 
> > 2.1.38
> 
> 暂时无法重现，以后我遇到了再看看吧。。。

好的，辛苦你了
