### ISSUE TITLE
动态以及回帖的bug

### ISSUE THREAD

**Issue by Know233** [Tangent-90/Coolapk-UWP#112]
1.动态显示不全(缺少自己最近创建的一条动态)，刷新一次个性签名处背景、头像、签名，会排列出现并叠加，见图片
2.回帖必定被吞（我。。。我的回复，能看到回帖内容但是在动态内看不到回复

**Comment by Know233** [comment]
![屏幕截图 2021-06-29 192139](https://user-images.githubusercontent.com/69572798/123789225-81c76f80-d90f-11eb-9728-61fb3c8ca112.png)

**Comment by wherewhere** [comment]
第一条已知，但是主分支停更了
第二条已解决，请更新测试版(或者ScreenShots分支里的安装包
