### ISSUE TITLE
无法发帖

### ISSUE THREAD

**Issue by ours1505** [Tangent-90/Coolapk-UWP#113]
![图片](https://user-images.githubusercontent.com/61079068/124689151-98228c00-df0a-11eb-92ba-e13b7f785c02.png)
没有地方尤验证码

**Comment by wherewhere** [comment]
无法解决，因为我没这个问题。。。

**Comment by tangli159** [comment]
> 无法解决，因为我没这个问题。。。

好像只要用uwp版本回帖子，必被屏蔽。我uwp回帖，转头去手机客户端看我的回复里面是有这条评论的。但是单独点开那个帖子一刷新，看不到我的评论。同样的话换手机发就没问题。

**Comment by wherewhere** [comment]
> > 无法解决，因为我没这个问题。。。
> 
> 好像只要用uwp版本回帖子，必被屏蔽。我uwp回帖，转头去手机客户端看我的回复里面是有这条评论的。但是单独点开那个帖子一刷新，看不到我的评论。同样的话换手机发就没问题。

这个问题已经解决了，但是由于其他bug还没法发布正式版，要发帖的话可以去用1.x，或者混进铺路根据地里找预览版<img alt="流汗滑稽" src="https://raw.fastgit.org/Tangent-90/Coolapk-UWP/master/src/CoolapkUWP/Assets/Emoji/1259.png" width="20px" />
