### ISSUE TITLE
一键安装报错了

### ISSUE THREAD

**Issue by wittytang** [Tangent-90/Coolapk-UWP#180]
### Describe the bug

使用教程里的一键安装方式。

### Steps to reproduce the bug

![image](https://github.com/Coolapk-UWP/Coolapk-UWP/assets/48836821/bca6b16a-b6ac-4bd5-ad0f-519b208171ad)

### App version

3.0.40

### Windows version

Windows 11 version 22H2 (22621, 2022 Update)

### Device

Desktop

**Comment by wherewhere** [comment]
安装包早就无了，手动安装吧
