### ISSUE TITLE
windows 10 1909上闪退

### ISSUE THREAD

**Issue by ghostshutter** [Tangent-90/Coolapk-UWP#20]
不知道1909升级改动了什么鬼，一批uwp闪退，包括这个XD，用的是别人离线升级的LTSC 1909

**Comment by wherewhere** [comment]
很遗憾，我打包的时候的环境就是1909😂

**Comment by ghostshutter** [comment]
__

> 很遗憾，我打包的时候的环境就是1909😂

好像是我的锅，.net环境没搞好，升级以后直接装的appxbundle
