### ISSUE TITLE
我可以帮忙上架MS Store，请求授权

### ISSUE THREAD

**Issue by copperion** [Tangent-90/Coolapk-UWP#33]
我有微软开发者账号，可以考虑上个架，这样安装就没那么麻烦了

**Comment by copperion** [comment]
emmm看了一下是MIT协议的，不用授权（受虐滑稽）

会保留Copyright的

**Comment by Tangent-90** [comment]
不了，都是bug

**Comment by copperion** [comment]
> 不了，都是bug

草（日语）

**Comment by copperion** [comment]
> 不了，都是bug

算了，我都开始走流程了，就差一点点了

**Comment by copperion** [comment]
在审核了

**Comment by copperion** [comment]
算了，提交了两回，头一回说应用分发不给上，然后第二回顺便把bug都给认证出来了（流汗滑稽）
![Screenshot_2020-02-03-12-43-15-814_com android chrome](https://user-images.githubusercontent.com/25267689/73626294-5fcaae80-4683-11ea-90da-b2d9595ad693.jpg)

**Comment by wherewhere** [comment]
(挖个坟，你当年应该选择隐藏应用的，这样基本不会审核应用内容就能上架。。。

**Comment by lonelyion** [comment]
<del>你怎么知道这个点我在逛GitHub（</del>

现在应该也可以，但是我最近一个月都没啥空

**Comment by wherewhere** [comment]
> <del>你怎么知道这个点我在逛GitHub（</del>
> 
> 现在应该也可以，但是我最近一个月都没啥空

好家伙，秒回啊。。。
(还是别上架了，WSA出现之后这玩意就算引流了。。。
