### ISSUE TITLE
1.0.24→1.1.25

### ISSUE THREAD

**Issue by wqk317** [Tangent-90/Coolapk-UWP#37]
我这个更新跟README上的不太一样呀
**示例是这样的:**
![图片](https://user-images.githubusercontent.com/13175615/76823873-6a668f00-6850-11ea-8ea1-9e2f21f32a5a.png)
**我的是这样的:**
![图片](https://user-images.githubusercontent.com/13175615/76823936-8a964e00-6850-11ea-8d22-e0f24d509f62.png)

**Comment by wqk317** [comment]
![图片](https://user-images.githubusercontent.com/13175615/76824063-efea3f00-6850-11ea-874a-4d3149ce0b90.png)

**Comment by wherewhere** [comment]
前面那个1.0.24是修改后的，现在包名已经换了，这个问题过期了。。。
