### ISSUE TITLE
正文出现各种标签

### ISSUE THREAD

**Issue by MoonBigD** [Tangent-90/Coolapk-UWP#40]
![Uploading V70UOINEYNZ5%Y))3QYKB)G.png…](
![J(TTB%1$~J~{ E13_SJV (D](https://user-images.githubusercontent.com/46624248/77619468-376c7b80-6f73-11ea-9f7d-2324624040ca.png)
![A39Q DV@DZO8Z{WNZ81(4_R](https://user-images.githubusercontent.com/46624248/77619472-39ced580-6f73-11ea-9d66-335e813186f0.png)

)

1

**Comment by wazituzi** [comment]
右边这些是评论吧，只是排列方式是这样

**Comment by Tangent-90** [comment]
已修复
