### ISSUE TITLE
动态/图文中出现复数超链接时，所有的“查看链接”都指向文中第一个超链接

### ISSUE THREAD

**Issue by shibeta** [Tangent-90/Coolapk-UWP#42]
比如这篇图文《远超狗屁不通生成器，真正的AI自动写文章神器来啦！》
![捕获](https://user-images.githubusercontent.com/31058019/78954750-a4eddf80-7b0f-11ea-92a6-dab063068a10.PNG)
文中有三个链接，第一个是度盘，第二个是吾爱，第三个是github
但点击任何一个都只会打开第一个度盘链接

不过鼠标放在“查看链接”上提示的url是正确的

**Comment by Tangent-90** [comment]
已修复
