### ISSUE TITLE
能否上架win10商店

### ISSUE THREAD

**Issue by msydh** [Tangent-90/Coolapk-UWP#51]
现在都是自行安装，有点麻烦。上架商店安装升级就省心多了。
大佬如果对此有什么难处的话，请告诉我们，我们一起解决。

**Comment by Tangent-90** [comment]
这东西现在功能少bug多，不适合发上去<img alt="流汗滑稽" src="../raw/master/CoolapkUWP/Assets/Emoji/0057.png" width="20px"/>
~~（之前有大佬上传过，因为bug多被退回了~~
