### ISSUE TITLE
是否能适配高分辨率屏幕？

### ISSUE THREAD

**Issue by gaoxianglyx** [Tangent-90/Coolapk-UWP#53]
我使用的是4K 27寸屏幕，界面很不友好。
是否能适配高分辨率屏幕？

另外，不知是不是因为屏幕分辨率高，导致酷图的展示很模糊，每点开一张图片都需要右键看原图。
如果能在设置里面增加一个直接直接打开原图

**Comment by Tangent-90** [comment]
可能是因为缩放吧，调高一点缩放比看看？

**Comment by gaoxianglyx** [comment]
我是200%缩放，应该不是缩放比例问题吧
[首页截图](http://c-driver-servercp.qunarzz.com/c_driver_server_c_driver_server_9b14df527c12/a3f852a2e5fec1abd068829f063a37d8.png)
[酷图页面截图](http://c-driver-servercp.qunarzz.com/c_driver_server_c_driver_server_9b14df527c12/a3f852a2e5fec1abd068829f063a37d8.png)
