### ISSUE TITLE
感谢更新，新反馈4k屏幕，全屏时头条无法触发加载更多

### ISSUE THREAD

**Issue by gaoxianglyx** [Tangent-90/Coolapk-UWP#55]
![image](https://user-images.githubusercontent.com/14159090/85301930-0f8da500-b4db-11ea-80de-b006c3495d0e.png)
如图，设备时4k分辨率，27寸，200%缩放。
当应用全屏时（我隐藏了底部底栏），无法触发头条的加载机制，只会显示这么多的条数，往下也划不动。
当切换到窗口模式时可以正常操作。

看到设置里面已经有默认原图了，感谢更新

**Comment by Tangent-90** [comment]
现在换了布局，能滚动了😂

**Comment by gaoxianglyx** [comment]
新版可以了，感谢
