### ISSUE TITLE
最新版无法加载

### ISSUE THREAD

**Issue by hxys-edith** [Tangent-90/Coolapk-UWP#65]
![截图_2020-07-15_14,43,04](https://user-images.githubusercontent.com/26269474/87601270-9f250e80-c6a9-11ea-92dc-fd948f979757.png)

**Comment by Tangent-90** [comment]
问一下，你的时区设置是什么？

**Comment by Moooebie** [comment]
> 问一下，你的时区设置是什么？

我遇到了同一个问题，我的时区设置是加拿大大西洋时间，开启夏令时（UTC -3:00）如果关闭夏令时（UTC -4:00）则可以正常使用APP。上一个版本不存在此问题。

**Comment by Moooebie** [comment]
> 问一下，你的时区设置是什么？

![image](https://user-images.githubusercontent.com/62904164/87686771-4910a380-c75b-11ea-98f9-5bd848d1e9c7.png)

**Comment by hxys-edith** [comment]
加拿大大西洋时间，开启夏令时

**Comment by Tangent-90** [comment]
下个版本修复

**Comment by hxys-edith** [comment]
感谢
