### ISSUE TITLE
【Bug】 应用闪退

### ISSUE THREAD

**Issue by hxys-edith** [Tangent-90/Coolapk-UWP#70]
在摄影话题里多点几下刷新就会闪退

复现率100%

望尽快修复

**Comment by hxys-edith** [comment]
有没有人来看看啊，很影响体验的

**Comment by CodeForCSharp** [comment]
已经尝试修复这个问题了，是因为x:load存在一些情况会无法正确释放对象，然后产生错误。目前已经合并，等发版。

**Comment by hxys-edith** [comment]
多谢

**Comment by arbaleast** [comment]
我也出现了闪退，是安装后，打开加载酷安图标时闪退
![image](https://user-images.githubusercontent.com/57560360/117525268-f824b100-aff3-11eb-85b2-499b4c026aee.png)
