### ISSUE TITLE
应用内存消耗过大

### ISSUE THREAD

**Issue by CodeForCSharp** [Tangent-90/Coolapk-UWP#73]
目前应用会缓存GET请求，但是似乎并没有正确释放，例如超时清除等。
导致应用缓存了大量数据，消耗了大量的内存。
建议不要对请求使用缓存策略。

**Comment by Tangent-90** [comment]
已经在新的代码里加入了一个 timer 来清理过时（加载时间在 2 分钟前）的缓存。😂
