### ISSUE TITLE
请问安装的证书，去哪删除😂

### ISSUE THREAD

**Issue by RudeTheJack** [Tangent-90/Coolapk-UWP#80]
同志们辛苦了，不过软件跟我的预期差距很大，所以还是先卸载了，由于患有强迫症，就想弄的干干净净的，请问安装前安装的这个证书该怎么删除啊😂找了半天都没找到和coolapk相关的

**Comment by CodeForCSharp** [comment]
如果是按照标准的模式安装的，Win+ R => certmgr.msc => 受信任的根证书颁发机构  然后删掉就是了

**Comment by RudeTheJack** [comment]
> 如果是按照标准的模式安装的，Win+ R => certmgr.msc => 受信任的根证书颁发机构  然后删掉就是了

这个受信任的根证书颁发机构里面有好多，我不知道该删哪一个

**Comment by PRSJMC** [comment]
> > 如果是按照标准的模式安装的，Win+ R => certmgr.msc => 受信任的根证书颁发机构  然后删掉就是了
> 
> 这个受信任的根证书颁发机构里面有好多，我不知道该删哪一个

直接看证书的属性，可以发现发布者是where，删掉这个就好了

**Comment by RudeTheJack** [comment]
> 如果是按照标准的模式安装的，Win+ R => certmgr.msc => 受信任的根证书颁发机构  然后删掉就是了

好的，谢谢，我待会去试试
加油啊，期待你们的完成品
