### ISSUE TITLE
简单解决证书过期无法安装

### ISSUE THREAD

**Issue by Spoience** [Tangent-90/Coolapk-UWP#86]
暂时关闭Windows的Internet自动同步时间，修改系统时间为2020年10月5日之前（比如9月5号），根据项目README.md的方法导入证书然后安装UWP酷安，安装完成将系统时间设置为自动同步即可解决！

**Comment by zhaixingren** [comment]
有用啊 老哥

**Comment by taoliescape** [comment]
确实有用

**Comment by waidaofumie** [comment]
确实可以

**Comment by DebuAqua** [comment]
并不是很喜欢这种解决方法，如果是开发者自签名的证书，为何一直没有提供有效期更新过的证书？

**Comment by PRO-2684** [comment]
亲测可行，但感觉不是长久之计

**Comment by Spoience** [comment]
目前似乎看起来项目作者已经停止维护该项目仓库，由于 Release 的版本目前的问题有点多，已经不太建议继续使用。但我们仍然感谢项目作者给我们提供过的体验！因此此 Issue 将关闭，不再推荐这种方式安装过期证书，在此项目继续更新前，也推荐暂时停止使用，那会很影响你的体验！
