### ISSUE TITLE
该更新了。证书过期。以及一些小建议？

### ISSUE THREAD

**Issue by orzgithub** [Tangent-90/Coolapk-UWP#87]
如题。虽然目前证书过期可以用改日期到10月4日之前的方法来安装。不过还是更新一下证书比较好。
此外，我这边存在从 _关注_ 标签到 _头条_ 标签时会提示 **无法访问该数据** （包括这种情况下刷新），需要再次点击 _头条_ 标签才可以顺利完成加载，不知道是不是个例。
布局对电脑还不是很好，建议优化（例如在最大化下把话题页面做成悬浮小块排列在头条右侧？）
建议把置顶之类的功能支持上（虽然电脑上作用相对小）
_关注_ 标签的点击逻辑建议改为其他页面下点击只是切换到全部关注，在关注页面下点击再展开具体关注分类。
目前 _分享_ 按钮似乎没什么用？可以移除的。
说起来，我是不是提太多建议了…

**Comment by SuperWangCC** [comment]
如果还在活跃maintain的话更新一下证书吧。

**Comment by AnotiaWang** [comment]
https://github.com/Tangent-90/Coolapk-UWP/issues/86#issue-717120943

**Comment by wherewhere** [comment]
大部分应该都实现了(不过主分支出了大Bug，而且已经停更了<img alt="幽灵" src="https://raw.fastgit.org/Tangent-90/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png" width="20px" /><img alt="幽灵" src="https://raw.fastgit.org/Tangent-90/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png" width="20px" /><img alt="幽灵" src="https://raw.fastgit.org/Tangent-90/Coolapk-UWP/master/CoolapkUWP/CoolapkUWP/Assets/Emoji/0999.png" width="20px" />
