### ISSUE TITLE
证书过期了

### ISSUE THREAD

**Issue by yukiryo** [Tangent-90/Coolapk-UWP#89]

**Comment by All2b9s** [comment]
相同的问题，无法安装
![Snipaste_2021-01-20_03-09-39](https://user-images.githubusercontent.com/68979304/105152551-f975b080-5acc-11eb-81e1-17b9b2b5b3e1.jpg)

**Comment by Haerbin23456** [comment]
我也是
```PowerShell
找到了捆绑: E:\IDM\Compressed\CoolapkUWP_2.0.34.0_Test\CoolapkUWP_2.0.34.0_x86_x64_arm.appxbundle
找到证书: E:\IDM\Compressed\CoolapkUWP_2.0.34.0_Test\CoolapkUWP_2.0.34.0_x86_x64_arm.cer
错误: 开发人员证书“E:\IDM\Compressed\CoolapkUWP_2.0.34.0_Test\CoolapkUWP_2.0.34.0_x86_x64_arm.cer”已到期。一个可能的原因是系统时钟未设置为正确的日期和时间。如果系统设置正确，请与应用程序所有者联系以使用有效的证书重新创建包或捆绑。
按 Enter 键继续...:
```
![image](https://user-images.githubusercontent.com/60066765/105570697-1d175000-5d86-11eb-8ecd-b5c47f2d172e.png)

**Comment by AnotiaWang** [comment]
> _No description provided._



> 相同的问题，无法安装
> ![Snipaste_2021-01-20_03-09-39](https://user-images.githubusercontent.com/68979304/105152551-f975b080-5acc-11eb-81e1-17b9b2b5b3e1.jpg)



> 我也是
> 
> ```powershell
> 找到了捆绑: E:\IDM\Compressed\CoolapkUWP_2.0.34.0_Test\CoolapkUWP_2.0.34.0_x86_x64_arm.appxbundle
> 找到证书: E:\IDM\Compressed\CoolapkUWP_2.0.34.0_Test\CoolapkUWP_2.0.34.0_x86_x64_arm.cer
> 错误: 开发人员证书“E:\IDM\Compressed\CoolapkUWP_2.0.34.0_Test\CoolapkUWP_2.0.34.0_x86_x64_arm.cer”已到期。一个可能的原因是系统时钟未设置为正确的日期和时间。如果系统设置正确，请与应用程序所有者联系以使用有效的证书重新创建包或捆绑。
> 按 Enter 键继续...:
> ```
> 
> ![image](https://user-images.githubusercontent.com/60066765/105570697-1d175000-5d86-11eb-8ecd-b5c47f2d172e.png)

https://github.com/Tangent-90/Coolapk-UWP/issues/86#issue-717120943

**Comment by wherewhere** [comment]
签名已更新
