### ISSUE TITLE
证书过期了 安装不了啊  

### ISSUE THREAD

**Issue by GlamoroGG** [Tangent-90/Coolapk-UWP#90]

**Comment by AnotiaWang** [comment]
https://github.com/Tangent-90/Coolapk-UWP/issues/86#issue-717120943

**Comment by ni426** [comment]
把你电脑的时间改一下就可以了

**Comment by wherewhere** [comment]
签名已更新

**Comment by wherewhere** [comment]
【UWP】手把手教你回到过去安装签名过期的UWP https://b23.tv/KvqZxU
