### ISSUE TITLE
install.ps1安装提示开发人员证书已到期

### ISSUE THREAD

**Issue by kuki6** [Tangent-90/Coolapk-UWP#96]
不知道是不是只有我遇到这个问题，powershell运行提示：
错误: 开发人员证书“C:\User\Downloads\CoolapkUWP_2.0.34.0_Test\CoolapkUWP_2.0.34.0_x86_x64_arm.cer”已到期。一个可 能的原因是系统时钟未设置为正确的日期和时间。如果系统设置正确，请与应用程序所有者联系以使用有效的证书重新创建包或捆绑。

**Comment by jizizr** [comment]
我也是

**Comment by falseAlarmTonight** [comment]
我也是这样

**Comment by wherewhere** [comment]
签名已更新
