### ISSUE TITLE
更新包提示不受信任，证书已安装

### ISSUE THREAD

**Issue by zhangyisui** [Tangent-90/Coolapk-UWP#97]

**Comment by zhangyisui** [comment]
重新安装证书解决问题，注意要为所有用户安装
顺便提一下，卸载旧版安装新版要先重启否则无法安装

**Comment by zhuangside** [comment]
> 重新安装证书解决问题，注意要为所有用户安装 顺便提一下，卸载旧版安装新版要先重启否则无法安装

请问如何卸载呢
