### ISSUE TITLE
没法登陆

### ISSUE THREAD

**Issue by yaoplusplus** [Tangent-90/Coolapk-UWP#98]
点击登陆没有反应啊

**Comment by wherewhere** [comment]
能登录啊，说具体一点。。。

**Comment by yaoplusplus** [comment]
> 能登录啊，说具体一点。。。

我明白了，昨天似乎是因为我开了代理，所以登录页面连不上服务器，出现无响应的情况，谢谢

**Comment by yaoplusplus** [comment]
> > 能登录啊，说具体一点。。。
> 
> 我明白了，昨天似乎是因为我开了代理，所以登录页面连不上服务器，出现无响应的情况，谢谢

目前我可以正常登录了
