### ISSUE TITLE
顶部Tab栏的问题和保存原图问题

### ISSUE THREAD

**Issue by falling7down** [Tangent-90/Coolapk-UWP#99]
窗口收缩至最小宽度时，点击顶部tab栏的“更多”，界面就会卡住，什么也操作不了，只能关闭窗口；
在未右键查看原图前，无论点击顶部的保存原图选项还是右键弹出菜单里保存原图，都是保存的缩略图，不到100K，查看原图后保存显示有1M多。

**Comment by wherewhere** [comment]
已经把保存原图改成保存图片了<img alt="流汗滑稽" src="https://raw.fastgit.org/Tangent-90/Coolapk-UWP/master/src/CoolapkUWP/Assets/Emoji/1259.png" width="20px" />
如果要改也是先获取原图再保存图片，手动折腾一下不好吗<img alt="流汗滑稽" src="https://raw.fastgit.org/Tangent-90/Coolapk-UWP/master/src/CoolapkUWP/Assets/Emoji/1259.png" width="20px" />
